<?php
session_start();
require_once("config/db.php");
require_once("layout.php");
if (!isset($_SESSION['user'])) { header("Location: login.php"); exit(); }

$user = $_SESSION['user'];
$role = $user['role'];

if (!in_array($role, ['admin', 'accountant', 'hr'])) {
   header("Location: dashboard.php");
   exit();
}

$msg = ""; $msgType = "success";

// Handle approve/reject
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'], $_POST['record_id'])) {
   $action = $_POST['action'];
   $id     = $_POST['record_id'];
   if (in_array($action, ['approved', 'rejected'])) {
       try {
           updateDoc($manager, $dbName, $payrollCollection,
               ['_id' => new MongoDB\BSON\ObjectId($id)],
               [
                   'status'      => $action,
                   'reviewed_by' => $user['username'],
                   'reviewed_at' => date('Y-m-d H:i:s')
               ]
           );
           $msg = "Payroll record " . ucfirst($action) . ".";
           $msgType = $action === 'approved' ? 'success' : 'warning';
       } catch (Exception $e) {
           $msg = "Error updating record.";
           $msgType = "danger";
       }
   }
}

$filterStatus = $_GET['status'] ?? 'pending';
$filter = [];
if ($filterStatus !== 'all') $filter['status'] = $filterStatus;

$records = findDocs($manager, $dbName, $payrollCollection, $filter, ['sort' => ['created_at' => -1]]);

// Counts for tabs
$pendingCount  = count(findDocs($manager, $dbName, $payrollCollection, ['status' => 'pending']));
$approvedCount = count(findDocs($manager, $dbName, $payrollCollection, ['status' => 'approved']));
$rejectedCount = count(findDocs($manager, $dbName, $payrollCollection, ['status' => 'rejected']));

layoutHeader('Payroll Approval');
?>

<div class="d-flex justify-content-between align-items-center mb-4">
   <h4 class="mb-0"><i class="bi bi-check2-circle me-2"></i>Payroll Approval</h4>
</div>

<!-- Status Tabs -->
<ul class="nav nav-tabs mb-3">
   <li class="nav-item">
       <a class="nav-link <?= $filterStatus === 'pending' ? 'active' : '' ?>" href="?status=pending">
           Pending <span class="badge bg-warning text-dark ms-1"><?= $pendingCount ?></span>
       </a>
   </li>
   <li class="nav-item">
       <a class="nav-link <?= $filterStatus === 'approved' ? 'active' : '' ?>" href="?status=approved">
           Approved <span class="badge bg-success ms-1"><?= $approvedCount ?></span>
       </a>
   </li>
   <li class="nav-item">
       <a class="nav-link <?= $filterStatus === 'rejected' ? 'active' : '' ?>" href="?status=rejected">
           Rejected <span class="badge bg-danger ms-1"><?= $rejectedCount ?></span>
       </a>
   </li>
   <li class="nav-item">
       <a class="nav-link <?= $filterStatus === 'all' ? 'active' : '' ?>" href="?status=all">All</a>
   </li>
</ul>

<?php if ($msg): ?>
<div class="alert alert-<?= $msgType ?> alert-dismissible fade show" role="alert">
   <?= htmlspecialchars($msg) ?>
   <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<?php endif; ?>

<div class="card shadow-sm">
   <div class="card-body p-0">
       <div class="table-responsive">
           <table class="table table-hover align-middle mb-0">
               <thead class="table-light">
                   <tr>
                       <th>#</th>
                       <th>Employee</th>
                       <th>Month</th>
                       <th>Gross</th>
                       <th>Net Pay</th>
                       <th>Generated By</th>
                       <th>Status</th>
                       <?php if (in_array($role, ['admin', 'accountant'])): ?>
                       <th>Action</th>
                       <?php endif; ?>
                   </tr>
               </thead>
               <tbody>
               <?php if (empty($records)): ?>
               <tr>
                   <td colspan="8" class="text-center py-5 text-muted">
                       <i class="bi bi-check2-all display-6 d-block mb-2"></i>
                       No <?= $filterStatus !== 'all' ? $filterStatus : '' ?> records found.
                   </td>
               </tr>
               <?php else: ?>
               <?php foreach ($records as $i => $r): ?>
               <?php
                   $status = $r->status ?? 'pending';
                   $badgeClass = match($status) {
                       'approved' => 'bg-success',
                       'rejected' => 'bg-danger',
                       default    => 'bg-warning text-dark'
                   };
               ?>
               <tr>
                   <td class="text-muted"><?= $i + 1 ?></td>
                   <td>
                       <strong><?= htmlspecialchars($r->name ?? '—') ?></strong><br>
                       <small class="text-muted"><?= htmlspecialchars($r->emp_id ?? '') ?></small>
                   </td>
                   <td><?= htmlspecialchars($r->month ?? '—') ?></td>
                   <td>₹<?= number_format($r->gross ?? 0) ?></td>
                   <td><strong>₹<?= number_format($r->net_pay ?? 0) ?></strong></td>
                   <td><small><?= htmlspecialchars($r->generated_by ?? '—') ?></small></td>
                   <td><span class="badge <?= $badgeClass ?>"><?= ucfirst($status) ?></span></td>
                   <?php if (in_array($role, ['admin', 'accountant'])): ?>
                   <td>
                       <?php if ($status === 'pending'): ?>
                       <form method="POST" class="d-inline">
                           <input type="hidden" name="record_id" value="<?= $r->_id ?>">
                           <button name="action" value="approved" class="btn btn-success btn-sm"
                                   onclick="return confirm('Approve this payroll?')">
                               <i class="bi bi-check-lg"></i> Approve
                           </button>
                           <button name="action" value="rejected" class="btn btn-danger btn-sm ms-1"
                                   onclick="return confirm('Reject this payroll?')">
                               <i class="bi bi-x-lg"></i> Reject
                           </button>
                       </form>
                       <?php else: ?>
                       <small class="text-muted">by <?= htmlspecialchars($r->reviewed_by ?? '—') ?></small>
                       <?php endif; ?>
                   </td>
                   <?php endif; ?>
               </tr>
               <?php endforeach; ?>
               <?php endif; ?>
               </tbody>
           </table>
       </div>
   </div>
</div>

<?php layoutFooter(); ?>